<?php
return [
	'personalities' => [
		[
			"name" => "INTJ",
			"breakdown" => "Introverted Intuitive Thinking Judger",
			"definition" => "An Architect (INTJ) is a person with the Introverted, Intuitive, Thinking, and Judging personality traits. These thoughtful tacticians love perfecting the details of life, applying creativity and rationality to everything they do. Their inner world is often a private, complex one.

			It can be lonely at the top. As one of the rarest personality types - and one of the most capable - Architects (INTJs) know this all too well. Rational and quick-witted, Architects may struggle to find people who can keep up with their nonstop analysis of everything around them.",
			"weaknesses" => "Arrogant - Architects might be knowledgeable, but they're not infallible. Their self-assurance can blind them to useful input from other people - especially anyone they deem to be intellectually inferior. These personalities can also become needlessly harsh or single-minded in trying to prove others wrong.

			Dismissive of Emotions - For Architects, rationality is king. But emotional context often matters more than people with this personality type care to admit. Architects can get impatient with anyone who seems to value feelings more than facts. Unfortunately, ignoring emotion is its own type of bias - one that can cloud Architects' judgment.
			
			Overly Critical - These personalities tend to have a great deal of self-control, particularly when it comes to thoughts and feelings. When the people in their lives fail to match their level of restraint, Architects can become scathingly critical. But this criticism is often unfair, based on arbitrary standards rather than a full understanding of human nature.
			
			Combative - Architects hate blindly following anything without understanding why. This includes restrictions and the authority figures who impose them. People with this personality type can get caught up in arguing about useless rules and regulations - but sometimes these battles are distractions from more important matters.
			
			Romantically Clueless - Architects' relentless rationality can lead them to be frustrated by romance. Especially in the early stages of a relationship, they may struggle to understand what's going on and how to behave. And if their relationships fall apart for reasons they don't understand, they can become cynical about matters of the heart, even questioning the importance of love and connection.",
			"strength" => "Rational - Architects see nearly any situation as an opportunity to expand their knowledge and hone their rational thinking skills. 

			Informed - Rather than hunches or half-baked assumptions, they base their conclusions on research and analysis. 
			
			Independent - Conformity is more or less synonymous with mediocrity. Creative and self-motivated, Architects strive to do things their own way.
			
			Determined - Ambitious and goal-oriented. Whenever an idea or pursuit captures their imagination, they dedicate themselves to mastering the subject and gaining relevant skills.
			
			Curious - Architects are open to new ideas - as long as those ideas are rational and evidence-based, that is. Skeptical by nature, these personality types are especially drawn to offbeat or contrarian points of view. They're even open to changing their own opinions when the facts prove them wrong.
			
			Versatile - Architects love diving into all sorts of challenges. Their curiosity and determination can help people with this personality type succeed in a wide range of endeavors.",
			"interpersonal_attributes" => "Sharp-witted and darkly funny, Architects (INTJs) aren't everyone's cup of tea - and they're okay with that. For the most part, people with this personality type aren't obsessed with being popular. They don't spend their time and energy on just anyone, and they can be difficult to get to know.

			But this doesn't mean that Architects are antisocial or friendless. In fact, few things are more exhilarating to Architect personalities than the spark they feel when they connect with someone who really gets them.
			
			Architects tend to have strong opinions about what works, what doesn't, what they're looking for, and what they're not. This mindset gives them a clear picture of what they expect from their social lives and their friends - and it can also lead them to reject anyone who doesn't seem to meet these expectations. From the outside, people with this personality type may seem dismissive, but they would say they're just being decisive.
			
			In friendship, Architects are looking for an intellectual equal as much as anything else. These personalities crave mental stimulation, and they can become bored by anyone who can't keep up with the workings of their minds. Architects need to share their expansive ideas - making small talk is something they typically avoid.",
			"workplace_attributes" => "What Architects (INTJs) want - wherever they may be in their careers - is to pursue their professional goals according to their own standards. And if any personality type has high standards for themselves, it's almost certainly Architects.

			In theory, this attitude makes for a model employee and coworker. And in many ways, Architects are exactly that. But some personality types may find it a challenge to work with Architects. Architects may be harsh or dismissive toward people they don't respect - and unfortunately, losing their respect can be all too easy. In particular, they have little time for coworkers who prioritize convenience over innovation or socializing over success.
			
			Architect Subordinates
			Architects are known for their independence. Even in entry-level jobs, they may chafe at anyone who tries to limit their freedom. Their worst nightmare would be a micromanaging boss who monopolizes their time with pointless meetings, insists on useless rules, and appraises employees' performance based on how likable they seem rather than their actual merits.
			
			Architect (INTJ) workplace habits
			Titles mean little to Architects, and they often struggle to defer to a manager they don't respect. They might also find it difficult to restrain themselves from offering their bosses feedback and criticism - an approach that, depending on the boss, can backfire.
			
			In the real world, not all bosses will be as logical or open-minded as Architects might prefer. But that doesn't mean that people with this personality type should allow a less-than-ideal manager to hold them back.
			
			Architects may need to use all of their creativity and ingenuity to expand their responsibilities and develop their expertise - even if they don't have the independence they crave. To do this, they may need to prioritize building a productive and respectful relationship with their manager, no matter how far from perfect that person may be."
		],
		[
			"name" => "INTP",
			"breakdown" => "Introverted Intuitive Thinking Perceiver",
			"definition" => "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores",
			"weaknesses" => "Disconnected - Logicians can get lost in their own train of thought, even when they're with other people. When these personalities finally resurface with something to say, they may find that the conversation has moved on without them. This can cause them to feel disconnected from other people, especially in large social gatherings.
			Insensitive - People with this personality type see rationality as the key to a better, happier world. At times, they may underestimate the importance of such irrational values as emotion, compassion, etiquette, and tradition. As a result, they may inadvertently come across as insensitive or unkind, even though their intentions are generally good.
			Dissatisfied - Logicians can't help but imagine how things could be better than they already are. These personalities are constantly on the lookout for problems to solve, topics to learn, and new ways to approach things. Taken too far, this mindset can become overwhelming, with Logicians constantly trying to reinvent the wheel rather than reliably addressing their needs and responsibilities.
			Impatient - Logicians take pride in their knowledge and in sharing their ideas. When it comes to explaining their rationale, however, they aren't always patient. If their conversation partner doesn't follow along or seem sufficiently interested, Logicians may give up with a dismissive \"never mind.\"
			Perfectionistic - Logicians want to get things done, but their quest for perfection can get in the way. At times, these personalities may get so lost in analyzing various options that they never reach a decision. They may also give up on projects that don't match the ideal vision in their mind.",
			"strength" => "Analytical - Logicians analyze everything that they come across, from research data to the behavior of the people around them. This gives them a knack for spotting unexpected patterns and connections that other personality types might overlook.
			Original - Thanks to their unrelenting imagination, Logicians can come up with creative, counterintuitive ideas that wouldn't occur to most people. Not all of these ideas are feasible, of course, but Logicians' willingness to think outside the box can produce remarkable innovations.
			Open-Minded - Logicians are driven by curiosity and an intense desire to learn everything that they can. People with this personality type tend to be receptive to new ideas and ways of doing things - as long as those ideas are supported by sound reasoning.
			Curious - These personalities are always casting about for new pursuits, hobbies, and areas of research. One week, they might be obsessed with geophysics, and the next, they might lose themselves in videos about guitar building. When inspiration strikes, Logicians go all in on their newfound interest, learning everything that they can.
			Objective - Logicians care about the truth. Rather than taking comfort in ideology or received ideas, they want to understand what's really going on beneath the surface of things. As a result, they can be relied upon to combat bias and misinformation, even when it isn't easy to do so - and they expect other people to be honest with them in return.",
			"interpersonal_attributes" => "Like anyone, Logicians look to their friends for companionship and support. But people with this personality type prize something else as well: intellectual depth. Not everyone will meet Logicians' standards for a potential friend, but when someone does, the connection can spark instantly, surprising everyone who thought they had this seemingly distant personality type pegged.

			Choosy or Selective?
			Perhaps because they don't mind the company of their own thoughts, Logicians don't surround themselves with people just for the sake of it. As a result, it's not always easy to become close friends with these personalities. But when Logicians do open up, they can be lively, imaginative friends who always have something interesting or unexpected to say.
			
			Logician (INTP) friends
			Logicians' best friends tend to share their passion for new ideas, riddles, and solutions. But that doesn't mean that people with this personality type only seek out friends who agree with them. Logicians don't mind having their ideas challenged - in fact, they have a great deal of respect for people who make them rethink their assumptions and keep them on their toes.
			
			Logician friendships are knowledge-based, buoyed by the exchange of ideas, theories, and concepts.",
			"workplace_attributes" => "For Logicians, the ingredients for workplace satisfaction are fairly simple. People with this personality type crave intellectual stimulation, freedom to pursue their ideas, and opportunities to solve challenging puzzles. And if they can fulfill these needs with minimal social obligations and humdrum administrative tasks, so much the better.

			Though some Logicians may scoff at the notion, they often do their best work in collaboration with other people. These personalities tend to live in their heads, coming up with thoughts and insights faster than they know what to do with them. Logicians may sometimes feel irritated when managers or coworkers force them to slow down and figure out how to implement their ideas - but in the long term, such colleagues can be the secret to Logicians' success.
			
			Logician (INTP) workplace habits
			Logician Subordinates
			Under the right conditions, Logician employees are innovative and resourceful, easily wrapping their minds around whatever complex problems are placed in front of them. But in work environments that limit their independence or force them to do \"grunt work,\" these personalities may lose motivation quickly.
			
			This can create an unfortunate catch-22. Logicians are often tempted to put off tasks that seem boring or beneath them, but until they \"pay their dues\" by doing these tasks, their bosses probably won't grant them the freedom and latitude that they crave. Although Logicians might wish that they could just skip ahead to the interesting stuff, they need to prove themselves to their managers first."
		],
		[
			"name" => "ENTJ",
			"breakdown" => "Extroverted Intuitive Thinking Judger",
			"definition" => "A Commander (ENTJ) is someone with the Extraverted, Intuitive, Thinking, and Judging personality traits. They are decisive people who love momentum and accomplishment. They gather information to construct their creative visions but rarely hesitate for long before acting on them.

			Commanders are natural-born leaders. People with this personality type embody the gifts of charisma and confidence, and project authority in a way that draws crowds together behind a common goal. However, Commanders are also characterized by an often ruthless level of rationality, using their drive, determination and sharp minds to achieve whatever end they've set for themselves.",
			"weaknesses" => "Stubborn and Dominant - Sometimes all this confidence and willpower can go too far, and Commanders are all too capable of digging in their heels, trying to win every single debate and pushing their vision, and theirs alone.
			Intolerant - \"It's my way or the highway\" - People with the Commander personality type are notoriously unsupportive of any idea that distracts from their primary goals, and even more so of ideas based on emotional considerations. Commanders won't hesitate a second to make that fact clear to those around them.
			Impatient - Some people need more time to think than others, an intolerable delay to quick-thinking Commanders. They may misinterpret contemplation as stupidity or disinterest in their haste, a terrible mistake for a leader to make.
			Arrogant - Commander personalities respect quick thoughts and firm convictions, their own qualities, and look down on those who don't match up. This relationship is a challenge for most other personality types who are perhaps not timid in their own right, but will seem so beside overbearing Commanders.
			Poor Handling of Emotions - All this bluster, alongside the assumed supremacy of rationalism, makes Commanders distant from their own emotional expression and sometimes downright scornful of others'. People with this personality type often trample others' feelings, inadvertently hurting their partners and friends, especially in emotionally charged situations.
			Cold and Ruthless - Their obsession with efficiency and unwavering belief in the merits of rationalism, especially professionally, makes Commanders incredibly insensitive in pursuing their goals, dismissing personal circumstances, sensitivities, and preferences as irrational and irrelevant.",
			"strength" => "Efficient - Commanders see inefficiency not just as a problem in its own right, but as something that pulls time and energy away from all their future goals, an elaborate sabotage consisting of irrationality and laziness. People with the Commander personality type will root out such behavior wherever they go.
			Energetic - Rather than finding this process taxing Commanders are energized by it, genuinely enjoying leading their teams forward as they implement their plans and goals.
			Self-Confident - Commanders couldn't do this if they were plagued by self-doubt - they trust their abilities, make known their opinions, and believe in their capacities as leaders.
			Strong-Willed - Nor do they give up when the going gets tough - Commander personalities strive to achieve their goals, but really nothing is quite as satisfying to them as rising to the challenge of each obstacle in their run to the finish line.
			Strategic Thinkers - Commanders exemplify the difference between moment-to-moment crisis management and navigating the challenges and steps of a bigger plan, and are known for examining every angle of a problem and not just resolving momentary issues, but moving the whole project forward with their solutions.
			Charismatic and Inspiring - These qualities combine to create individuals who are able to inspire and invigorate others, who people actually want to be their leaders, and this in turn helps Commanders to accomplish their often ambitious goals that could never be finished alone.",
			"interpersonal_attributes" => "As in most aspects of their lives, in friendship Commanders seek personal growth and inspiration, and they often have a plan for how to accomplish it. Friendships of circumstance, built on things like shared routines, are not Commanders' preferred method - rather, they pursue their friends, seek out individuals who share their passion for deep, meaningful discussions, and who enjoy learning and development as much as they do. It is not always easy to be Commanders' friends - they demand a lot from these relationships - but they pay a great deal of attention to their friendships, and it is unlikely that it will ever feel stagnant.

			Commander friendships are built on ideas, and a lot of what they find enjoyable is the repartee of putting thoughts forward and defending them from assault from every angle. People with the Commander personality type are very smart and highly critical, and they won't back down if they are put on the defensive - in fact, there's no better way to earn their respect.",
			"workplace_attributes" => "or people with the Commander personality type, the workplace is all but a natural habitat. Commanders' efficiency and clear communication are valued, their leadership is admired, and their ability to simply get things done is unrivaled. That being said, some situations are more appropriate for Commanders than others - these qualities all point to a managerial or executive role, making any position of comparative powerlessness highly undesirable.

			Subordinate positions are challenging for Commanders, and it takes active management to ensure their satisfaction and engagement. Ever the high achievers, Commander subordinates set out to learn new skills and to seek out new challenges and responsibilities, eager to prove that nothing is impossible with a little hard work. If things get a little slow, Commander personalities may slip into periods of absentmindedness, but when they feel involved in the projects around them, they prove well organized and well prioritized."
		],
		[
			"name" => "ENTP",
			"breakdown" => "Extroverted Intuitive Thinking Perceiver",
			"definition" => "A Debater (ENTP) is a person with the Extraverted, Intuitive, Thinking, and Prospecting personality traits. They tend to be bold and creative, deconstructing and rebuilding ideas with great mental agility. They pursue their goals vigorously despite any resistance they might encounter.

			No one loves the process of mental sparring more than the Debater personality type, as it gives them a chance to exercise their effortlessly quick wit, broad accumulated knowledge base, and capacity for connecting disparate ideas to prove their points. Debaters are the ultimate devil's advocate, thriving on the process of shredding arguments and beliefs and letting the ribbons drift in the wind for all to see. They don't always do this because they are trying to achieve some deeper purpose or strategic goal, though. Sometimes it's for the simple reason that it's fun.",
			"weaknesses" => "Very Argumentative - If there's anything Debaters enjoy, it's the mental exercise of debating an idea, and nothing is sacred. More consensus-oriented personality types rarely appreciate the vigor with which Debater personalities tear down their beliefs and methods, leading to a great deal of tension.
			Insensitive - Being so rational, Debaters often misjudge others feelings and push their debates well past others' tolerance levels. People with this personality type don't really consider emotional points to be valid in such debates either, which magnifies the issue tremendously.
			Intolerant - Unless people are able to back up their ideas in a round of mental sparring, Debaters are likely to dismiss not just the ideas but the people themselves. Either a suggestion can stand up to rational scrutiny or it's not worth bothering with.
			Can Find It Difficult to Focus - The same flexibility that allows Debaters to come up with such original plans and ideas makes them readapt perfectly good ones far too often, or to even drop them entirely as the initial excitement wanes and newer thoughts come along. Boredom comes too easily for Debaters, and fresh thoughts are the solution, though not always a helpful one.
			Dislike Practical Matters - Debaters are interested in what could be - malleable concepts like ideas and plans that can be adapted and debated. When it comes to hard details and day-to-day execution where creative flair isn't just unnecessary but actually counter-productive, Debater personalities lose interest, often with the consequence of their plans never seeing the light of day.",
			"strength" => "Knowledgeable - Debaters rarely pass up a good opportunity to learn something new, especially abstract concepts. This information isn't usually absorbed for any planned purpose as with dedicated studying, people with the Debater personality type just find it fascinating.
			Quick Thinkers - Debaters have tremendously flexible minds, and are able to shift from idea to idea without effort, drawing on their accumulated knowledge to prove their points, or their opponents', as they see fit.
			Original - Having little attachment to tradition, Debater personalities are able to discard existing systems and methods and pull together disparate ideas from their extensive knowledge base, with a little raw creativity to hold them together, to formulate bold new ideas. If presented with chronic, systemic problems and given rein to solve them, Debaters respond with unabashed glee.
			Excellent Brainstormers - Nothing is quite as enjoyable to Debaters as analyzing problems from every angle to find the best solutions. Combining their knowledge and originality to splay out every aspect of the subject at hand, rejecting without remorse options that don't work and presenting ever more possibilities, Debaters are irreplaceable in brainstorming sessions.
			Charismatic - People with the Debater personality type have a way with words and wit that others find intriguing. Their confidence, quick thought and ability to connect disparate ideas in novel ways create a style of communication that is charming, even entertaining, and informative at the same time.
			Energetic - When given a chance to combine these traits to examine an interesting problem, Debaters can be truly impressive in their enthusiasm and energy, having no qualms with putting in long days and nights to find a solution.",
			"interpersonal_attributes" => "Loyalty, support, emotional feedback - these are not what Debaters look for in their friendships. The last thing people with the Debater personality type want to hear is \"you're right\", not unless they have absolutely earned the distinction in a heated round of intellectual debate. If they're wrong, Debaters want to be told so, and they want every detail of the faults in their logic to be laid bare, partly in their quest for oftentimes arbitrary truth, and partly just so they have to work to defend that logic with counterpoint and parry.

			It's often easy for Debaters to test compatibility with a potential friend - they just need to test combatability. Debater personalities are quick-witted, and their primary means of expressing this is in the form of arguments and discussions, where they will easily spend an entire evening debating an idea they may not even believe in.",
			"workplace_attributes" => "Debaters have straightforward expectations in the workplace, but ones that aren't always easy to meet. Strong believers in meritocracy, people with the Debater personality type expect their ideas to be heard by those above them, expect robust debate among their peers, and demand that those they manage offer up new solutions and ideas regardless of their positions. While this isn't always how things play out in reality, Debaters know what to look for, and can avoid those strictly hierarchical institutions that they would otherwise struggle with.

			Debater Subordinates
			This dynamic is clearest with Debater subordinates, as they are comfortable challenging their managers' ideas and have a strong (and well-expressed) dislike for restrictive rules and guidelines. Debaters back this unorthodox behavior with their keen minds and curiosity, and are as capable of adopting new methods as they are of suggesting others do so. "
		],
		[
			"name" => "ISTP",
			"breakdown" => "Introverted Sensing Thinking Perceiver",
			"definition" => "A Virtuoso (ISTP) is someone with the Introverted, Observant, Thinking, and Prospecting personality traits. They tend to have an individualistic mindset, pursuing goals without needing much external connection. They engage in life with inquisitiveness and personal skill, varying their approach as needed.

			Virtuosos love to explore with their hands and their eyes, touching and examining the world around them with cool rationalism and spirited curiosity. People with this personality type are natural Makers, moving from project to project, building the useful and the superfluous for the fun of it, and learning from their environment as they go. ",
			"weaknesses" => "Stubborn - As easily as Virtuosos go with the flow, they can also ignore it entirely, and usually move in another direction with little apology or sensitivity. If someone tries to change Virtuosos' habits, lifestyle or ideas through criticism, they can become quite blunt in their irritation.
			Insensitive - Virtuosos use logic, and even when they try to meet others halfway with empathy and emotional sensitivity, it rarely seems to quite come out right, if anything is even said at all.
			Private and Reserved - Virtuoso personalities are notoriously difficult to get to know. They are true introverts, keeping their personal matters to themselves, and often just prefer silence to small talk.
			Easily Bored - Virtuosos enjoy novelty, which makes them excellent tinkerers, but much less reliable when it comes to focusing on things long-term. Once something is understood, Virtuosos tend to simply move on to something new and more interesting.
			Dislike Commitment - Long-term commitments are particularly onerous for Virtuosos. They prefer to take things day-by-day, and the feeling of being locked into something for a long time is downright oppressive. This can be a particular challenge in Virtuosos' romantic relationships.
			Risky Behavior - This stubbornness, difficulty with others' emotions, focus on the moment, and easy boredom can lead to unnecessary and unhelpful boundary-pushing, just for fun. Virtuosos have been known to escalate conflict and danger just to see where it goes, something that can have disastrous consequences for everyone around if they lose control of the situation.",
			"strength" => "Optimistic and Energetic - Virtuosos are usually up to their elbows in some project or other. Cheerful and good-natured, people with the Virtuoso personality type (especially Assertive ones) rarely get stressed out, preferring to go with the flow.
			Creative and Practical - Virtuosos are very imaginative when it comes to practical things, mechanics, and crafts. Novel ideas come easily, and they love using their hands to put them into action.
			Spontaneous and Rational - Combining spontaneity with logic, Virtuosos can switch mindsets to fit new situations with little effort, making them flexible and versatile individuals.
			Know How to Prioritize - This flexibility comes with some unpredictability, but Virtuoso personalities are able to store their spontaneity for a rainy day, releasing their energy just when it's needed most.
			Great in a Crisis - With all this hands-on creativity and spontaneity, it's no wonder that Virtuosos are naturals in crisis situations. People with this personality type usually enjoy a little physical risk, and they aren't afraid to get their hands dirty when the situation calls for it.
			Relaxed - Through all this, Virtuosos are able to stay quite relaxed. They live in the moment and go with the flow, refusing to worry too much about the future.",
			"interpersonal_attributes" => "When it comes to friendships, Virtuosos seem made for Bushnell's Law of game design: Easy to learn, difficult to master. With their well-rounded and interesting array of hobbies, people with the Virtuoso personality type have no trouble at all making acquaintances to share their activities with. It's getting beneath the surface to become Virtuosos' true friends that is the real challenge, leaving them with a lot of good will and friendly faces to call on, but only a few people who they feel truly understand them.

			A lot of this comes down to Virtuosos simply not wanting to be bound to any particular person or activity. Virtuoso personalities live in the present, enjoying whatever life brings, and feel no real obligation to shift course on account of others' plans. If friends don't want to do what Virtuosos are doing, then they are free to go do their own thing, and they'll hang out some other time. Sometimes their shifts in attitude can catch their friends flat-footed, but Virtuosos' motto remains \"everything can be changed\". ",
			"workplace_attributes" => "When it comes to the workplace, Virtuosos' top requirement is often a sense of unpredictability and excitement. This quality makes Virtuoso personalities' personal relationships challenging enough, even among close friends and immediate family - for those they've only come to know in a professional environment, it can be downright frustrating.

			Of course, this all comes down to knowing what makes them tick. With a little space and a hands-on problem to solve, Virtuosos can be some of the most productive people around.
			
			Virtuoso Subordinates
			As subordinates, what Virtuosos crave most is a little wiggle room. Relaxed and easy-going, people with the Virtuoso personality type are happy to stick around with surprising loyalty, as long as their employers and managers don't try to force them to commit to anything that can't be undone the next day. Strict rules, guidelines and formal agreements make Virtuosos feel cramped and bored."
		],
		[
			"name" => "ISFP",
			"breakdown" => "Introverted Sensing Feeling Perceiver",
			"definition" => "An Adventurer (ISFP) is a person with the Introverted, Observant, Feeling, and Prospecting personality traits. They tend to have open minds, approaching life, new experiences, and people with grounded warmth. Their ability to stay in the moment helps them uncover exciting potentials.

			Adventurer personalities are true artists, but not necessarily in the typical sense where they're out painting happy little trees. Often enough though, they are perfectly capable of this. Rather, it's that they use aesthetics, design and even their choices and actions to push the limits of social convention. Adventurers enjoy upsetting traditional expectations with experiments in beauty and behavior - chances are, they've expressed more than once the phrase \"Don't box me in!\"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores",
			"weaknesses" => "Fiercely Independent - Freedom of expression is often Adventurers' top priority. Anything that interferes with that, like traditions and hard rules, creates a sense of oppression for Adventurer personalities. This can make more rigidly structured academics and work a challenge.
			Unpredictable - Adventurers' dislike long-term commitments and plans. The tendency to actively avoid planning for the future can cause strain in Adventurers' romantic relationships and financial hardship later in life.
			Easily Stressed - Adventurers live in the present, full of emotion. When situations get out of control, people with this personality type (especially Turbulent ones) can shut down, losing their characteristic charm and creativity in favor of gnashing teeth.
			Overly Competitive - Adventurers can escalate small things into intense competitions, turning down long-term success in their search for glory in the moment, and are unhappy when they lose.
			Fluctuating Self-Esteem - It's demanded that skills be quantified, but that's hard to do with Adventurers' strengths of sensitivity and artistry. Adventurers' efforts are often dismissed, a hurtful and damaging blow, especially early in life. Adventurers can start to believe the naysayers without strong support.",
			"strength" => "Charming - People with the Adventurer personality type are relaxed and warm, and their \"live and let live\" attitude naturally makes them likable and popular.
			Sensitive to Others - Adventurers easily relate to others' emotions, helping them to establish harmony and good will, and minimize conflict.
			Imaginative - Being so aware of others' emotions, Adventurer personalities use creativity and insight to craft bold ideas that speak to people's hearts. While it's hard to explain this quality on a resume, this vivid imagination and exploratory spirit help Adventurers in unexpected ways.
			Passionate - Beneath Adventurers' quiet shyness beats an intensely feeling heart. When people with this personality type are caught up in something exciting and interesting, they can leave everything else in the dust.
			Curious - Ideas are well and good, but Adventurers need to see and explore for themselves whether their ideas ring true. Work revolving around the sciences may seem a poor match for their traits, but a boldly artistic and humanistic vision is often exactly what research needs to move forward - if Adventurers are given the freedom they need to do so.
			Artistic - Adventurers are able to show their creativity in tangible ways and with stunning beauty. Whether writing a song, painting an emotion, or presenting a statistic in a graph, Adventurers have a way of visualizing things that resonates with their audience.",
			"interpersonal_attributes" => "In friendship, Adventurers are some of the most comfortable people around. Laid back and spontaneous, people with the Adventurer personality type won't bog things down with arguments or structured long-term plans. Intellectually exhausting pastimes like debates over European economic policy won't hold their attention long. The here-and-now is what's important to Adventurers, and they love spending time with their friends doing casual, fun activities.

			Adventurer personalities believe in actions, not words. They talk about what is, not what could, should or will be, and then they actually do it. This passion for action is a blessing for Adventurers, since it helps them get past their shyness in meeting new people. ",
			"workplace_attributes" => "In the workplace, Adventurers seek out positions that give them as much wiggle room as possible to do things their own way. Button-down environments that revolve around tightly held traditions and strictly enforced procedures are unlikely to appeal to Adventurer personalities. Spontaneous, charming, and genuinely fun people to be around, Adventurers just want a chance to express those natural qualities, and to know that their efforts are appreciated.

			Adventurer Subordinates
			People with the Adventurer personality type don't like to be controlled, and this can be quite clear in subordinate positions - they loathe being micromanaged. At the same time, Adventurers aren't well-known for their long-term focus, but rather their adaptability and spontaneity. They'll use unconventional methods, sometimes risky ones, and existing rules are just someone else's way of doing things. Still, Adventurers find a way to make things happen. To manage Adventurer personalities successfully, there need to be clearly set goals, and otherwise an open sandbox."
		],
		[
			"name" => "ESTP",
			"breakdown" => "Extroverted Sensing Thinking Perceiver",
			"definition" => "An Entrepreneur (ESTP) is someone with the Extraverted, Observant, Thinking, and Prospecting personality traits. They tend to be energetic and action-oriented, deftly navigating whatever is in front of them. They love uncovering life's opportunities, whether socializing with others or in more personal pursuits.

			Entrepreneurs always have an impact on their immediate surroundings - the best way to spot them at a party is to look for the whirling eddy of people flitting about them as they move from group to group. Laughing and entertaining with a blunt and earthy humor, Entrepreneur personalities love to be the center of attention. If an audience member is asked to come on stage, Entrepreneurs volunteer - or volunteer a shy friend.",
			"weaknesses" => "Insensitive - Feelings and emotions come second to facts and \"reality\" for Entrepreneurs. Emotionally charged situations are awkward, uncomfortable affairs, and Entrepreneurs' blunt honesty doesn't help here. These personalities often have a lot of trouble acknowledging and expressing their own feelings as well.
			Impatient - Entrepreneurs move at their own pace to keep themselves excited. Slowing down because someone else \"doesn't get it\" or having to stay focused on a single detail for too long is extremely challenging for Entrepreneurs.
			Risk-prone - This impatience can lead Entrepreneurs to push into uncharted territory without thinking of the long-term consequences. Entrepreneur personalities sometimes intentionally combat boredom with extra risk.
			Unstructured - Entrepreneurs see an opportunity - to fix a problem, to advance, to have fun - and seize the moment, often ignoring rules and social expectations in the process. This may get things done, but it can create unexpected social fallout.
			May Miss the Bigger Picture - Living in the moment can cause Entrepreneurs to miss the forest for the trees. People with this personality type love to solve problems here and now, perhaps too much. All parts of a project can be perfect, but the project will still fail if those parts do not fit together.
			Defiant - Entrepreneurs won't be boxed in. Repetition, hardline rules, sitting quietly while they are lectured at - this isn't how Entrepreneurs live their lives. They are action-oriented and hands-on. Environments like school and much entry-level work can be so tedious that they're intolerable, requiring extraordinary effort from Entrepreneurs to stay focused long enough to get to freer positions.",
			"strength" => "Bold - People with the Entrepreneur personality type are full of life and energy. There is no greater joy for Entrepreneurs than pushing boundaries and discovering and using new things and ideas.
			Rational and Practical - Entrepreneurs love knowledge and philosophy, but not for their own sake. What's fun for Entrepreneur personalities is finding ideas that are actionable and drilling into the details so they can put them to use. If a discussion is completely arbitrary, there are better uses for Entrepreneurs' time.
			Original - Combining their boldness and practicality, Entrepreneurs love to experiment with new ideas and solutions. They put things together in ways no one else would think to.
			Perceptive - This originality is helped by Entrepreneurs' ability to notice when things change - and when they need to change! Small shifts in habits and appearances stick out to Entrepreneurs, and they use these observations to help create connections with others.
			Direct - This perceptive skill isn't used for mind games - Entrepreneurs prefer to communicate clearly, with direct and factual questions and answers. Things are what they are.
			Sociable - All these qualities pull together to make a natural group leader in Entrepreneurs. This isn't something that they actively seek - people with this personality type just have a knack for making excellent use of social interactions and networking opportunities.",
			"interpersonal_attributes" => "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores",
			"workplace_attributes" => "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores"
		],
		[
			"name" => "ESFP",
			"breakdown" => "Extroverted Sensing Feeling Perceiver",
			"definition" => "An Entertainer (ESFP) is a person with the Extraverted, Observant, Feeling, and Prospecting personality traits. These people love vibrant experiences, engaging in life eagerly and taking pleasure in discovering the unknown. They can be very social, often encouraging others into shared activities.

			If anyone is to be found spontaneously breaking into song and dance, it is the Entertainer personality type. Entertainers get caught up in the excitement of the moment, and want everyone else to feel that way, too. No other personality type is as generous with their time and energy as Entertainers when it comes to encouraging others, and no other personality type does it with such irresistible style.",
			"weaknesses" => "Sensitive - Entertainers (especially Turbulent ones) are strongly emotional, and very vulnerable to criticism - they can feel like they've been backed into a corner, sometimes reacting badly. This is probably Entertainers' greatest weakness, because it makes it so hard to address any other weaknesses brought to light.
			Conflict-Averse - Entertainers sometimes ignore and avoid conflict entirely. They tend to say and do what's needed to get out of such situations, then move on to something more fun.
			Easily Bored - Without constant excitement, Entertainers find ways to create it themselves. Risky behavior, self-indulgence, and the pleasures of the moment over long-term plans are all things Entertainers get into a little too often.
			Poor Long-Term Planners - In fact, Entertainer personalities rarely make detailed plans for the future. To them, things come as they come, and they rarely bother with taking the time to lay out steps and consequences, with the belief that they could change at any moment - even with things that can be planned.
			Unfocused - Anything that requires long-term dedication and focus is a particular challenge for Entertainers. In academics, dense, unchanging subjects like Classic Literature are much more difficult than more dynamic, relatable subjects like psychology. The trick for Entertainers is to find day-to-day joy in broader goals, and to tough it out with those tedious things that must be done.",
			"strength" => "Bold - Entertainers aren't known for holding back. Wanting to experience everything there is to experience, people with the Entertainer personality type don't mind stepping out of their comfort zones when no one else is willing.
			Original - Traditions and expectations are secondary to Entertainers, if a consideration at all. Entertainer personalities love to experiment with new styles, and constantly find new ways to stick out in the crowd.
			Aesthetics and Showmanship - Not stopping at mere outfits, Entertainers inject artistic creativity into their words and actions, too. Every day is a performance, and Entertainers love to put on a show.
			Practical - To Entertainers, the world is meant to be felt and experienced. Truth is stranger than fiction, and Entertainers prefer to see and do than to wax philosophical about \"what-ifs\".
			Observant - With all this focus on the here and now, on doing and acting, it makes sense that Entertainers are naturals when it comes to noticing real, tangible things and changes.
			Excellent People Skills - More so than things though, Entertainers love to pay attention to people. They are talkative, witty, and almost never run out of things to discuss. For people with this personality type, happiness and satisfaction stem from the time they spend with the people they enjoy being with.",
			"interpersonal_attributes" => "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores",
			"workplace_attributes" => "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores"
		],
		[
			"name" => "INFP",
			"breakdown" => "Introverted Intuitive Feeling Perceiver",
			"definition" => "A Mediator (INFP) is someone who possesses the Introverted, Intuitive, Feeling, and Prospecting personality traits. These rare personality types tend to be quiet, open-minded, and imaginative, and they apply a caring and creative approach to everything they do.

			Although they may seem quiet or unassuming, Mediators (INFPs) have vibrant, passionate inner lives. Creative and imaginative, they happily lose themselves in daydreams, inventing all sorts of stories and conversations in their minds. These personalities are known for their sensitivity - Mediators can have profound emotional responses to music, art, nature, and the people around them.",
			"weaknesses" => "Unrealistic - Nothing in this world is perfect - and that can be a difficult truth for Mediators to accept. People with this personality type can be hopeless romantics, with rose-colored visions of what their lives should be like. This can set Mediators up for disappointment when reality inevitably falls short of their dreams.
			Self-Isolating - Mediators long to connect with others, but they don't always know how. Especially in new environments, Mediators may be reluctant to put themselves out there in ways that would help them make new friends or become involved in a new community. As a result, people with this personality type may sometimes feel lonely or isolated.
			Unfocused - Mediators' imaginative, introspective nature doesn't always lend itself to productivity. Many Mediators get frustrated by how difficult they find it to buckle down and get things done. The problem isn't that they are incapable - rather, it's that they run into problems when they become so caught up in different ideas and ideals that they fail to commit to a course of action.
			Emotionally Vulnerable - The emotional attunement of these personalities is among their greatest strengths. But unless Mediators establish boundaries, they can be at risk of absorbing other people's negative moods or attitudes.
			Desperate to Please - Conflict tends to be stressful for Mediators, who yearn for harmony and acceptance. When someone dislikes or disapproves of them, these personalities may become fixated on trying to clear the air and change that person's mind. Unfortunately, Mediators' desire to please others can drain their energy, eclipsing their inner wisdom and their awareness of their own needs.
			Self-Critical - Mediators believe in their unique potential, and they desperately want to live up to it. But this can cause them to have unrealistic expectations for themselves. When Mediators fail to live up to these visions, they may accuse themselves of being useless or selfish or woefully inadequate. Taken too far, this self-criticism can discourage Mediators, leading them to give up on even their dearest dreams.",
			"strength" => "Empathetic - Mediators don't just care about other people in an abstract sense. These personalities can actually feel another person's emotions, from joy and elation to sorrow and regret. Because of this sensitivity, Mediators tend to be thoughtful and kindhearted, and they hate the idea of hurting anyone, even unintentionally.
			Generous - Mediators rarely enjoy succeeding at other people's expense. They feel called to share the good things in their lives, give credit where it's due, and uplift the people around them. These personalities want to contribute to a world where every voice is heard and no one's needs go unmet.
			Open-Minded - Tolerant and accepting, Mediators try not to judge anyone else's beliefs, lifestyles, or decisions. This is a personality type that prefers compassion to fault-finding, and many Mediators feel empathy even for those who have done wrong. Because they're so accepting, Mediators often become confidants for their friends and loved ones - and occasionally for total strangers.
			Creative - Mediators love to see things from unconventional perspectives. Few things give them more pleasure than allowing their minds to wander through all sorts of ideas and possibilities and daydreams. It's no wonder, then, that many Mediators are drawn to creative pursuits - or that this personality type is well represented among writers and artists.
			Passionate - When an idea or movement captures their imagination, Mediators want to give their whole heart to it. People with this personality type may not always be outspoken, but that doesn't diminish their strong feelings for a cause that speaks to their beliefs and convictions.
			Idealistic - Mediators strive to follow their conscience, even when doing the right thing isn't easy or convenient. They rarely lose sight of their desire to live a meaningful, purpose-filled life - one that helps others and leaves the world a better place.",
			"interpersonal_attributes" => "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores",
			"workplace_attributes" => "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores"
		],
		[
			"name" => "ENFP",
			"breakdown" => "Extroverted Intuitive Feeling Perceiver",
			"definition" => "A Campaigner (ENFP) is someone with the Extraverted, Intuitive, Feeling, and Prospecting personality traits. These people tend to embrace big ideas and actions that reflect their sense of hope and goodwill toward others. Their vibrant energy can flow in many directions.

			Campaigners (ENFPs) are true free spirits - outgoing, openhearted, and open-minded. With their lively, upbeat approach to life, they stand out in any crowd. But even though they can be the life of the party, Campaigners don't just care about having a good time. These personality types run deep - as does their longing for meaningful, emotional connections with other people.",
			"weaknesses" => "People-Pleasing - Most Campaigners are uncomfortable with the prospect of being disliked. To maintain the peace, they may compromise on things that matter to them or allow other people to treat them poorly. And when they fail to win someone over, they might lose sleep trying to figure out what to do about it.
			Unfocused - The thrill of a new project - especially one that involves collaborating with other people - can bring out the best in Campaigners. But this personality type is known for having ever-evolving interests, meaning that Campaigners may find it challenging to maintain discipline and focus over the long term.
			Disorganized - Campaigners' enthusiasm is legendary, but it doesn't extend to everything. Specifically, people with this personality type may try to avoid boring, practical matters, such as chores, maintenance, or paperwork. The resulting sense of disorganization can become a major source of stress in their lives.
			Overly Accommodating - Campaigner personalities feel called to uplift others, and they may find themselves saying yes whenever anyone asks them for guidance or help. But unless they set boundaries, even the most energetic Campaigners can become overcommitted, with too little time and energy to tackle the necessities of their own lives.
			Overly Optimistic - Optimism can be among this personality type's key strengths. But Campaigners' rosy outlook can lead them to make well-intentioned but naive decisions, such as believing people who haven't earned their trust. This trait can also make it difficult for Campaigners to accept hard but necessary truths - and to share those truths with others.
			Restless - With their positive, upbeat attitude, Campaigners rarely seem upset or dissatisfied on the outside. But their inner idealism can leave them with a nagging feeling that some major areas of their life just aren't good enough - whether that's their work, their home life, or their relationships.",
			"strength" => "Curious - Campaigners can find beauty and fascination in nearly anything. Imaginative and open-minded, these personalities aren't afraid to venture beyond their comfort zones in search of new ideas, experiences, and adventures.
			Perceptive - To people with this personality type, no one is unimportant - which might explain how they can pick up on even the subtlest shifts in another person's mood or expression. Because they're so sensitive to other people's feelings and needs, Campaigners can make full use of their caring, considerate nature.
			Enthusiastic - When something captures their imagination and inspires them, Campaigners want to share it with anyone who will listen. And they're just as eager to hear other people's ideas and opinions - even if those thoughts are wildly different from their own.
			Excellent Communicators - Campaigners brim with things to say, but they can be caring listeners as well. This gives them a nearly unmatched ability to have positive and enjoyable conversations with all sorts of people - even people who aren't particularly sociable or agreeable.
			Festive - Campaigners may live for deep, meaningful conversations, but they can also be spontaneous and lighthearted. These personalities know how to find fun and joy in the present moment - and few things give them more pleasure than sharing their joy with others.
			Good-Natured - All of these strengths come together to form a person who is warmhearted and approachable, with an altruistic spirit and a friendly disposition. Campaigners strive to get along with pretty much everyone, and their circles of acquaintances and friends often stretch far and wide.",
			"interpersonal_attributes" => "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores",
			"workplace_attributes" => "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores"
		],
		[
			"name" => "INFJ",
			"breakdown" => "Introverted Intuitive Feeling Judger",
			"definition" => "An Advocate (INFJ) is someone with the Introverted, Intuitive, Feeling, and Judging personality traits. They tend to approach life with deep thoughtfulness and imagination. Their inner vision, personal values, and a quiet, principled version of humanism guide them in all things.

			Advocates are the rarest personality types of all. Still, Advocates leave their mark on the world. They have a deep sense of idealism and integrity, but they aren't idle dreamers - they take concrete steps to realize their goals and make a lasting impact.",
			"weaknesses" => "Sensitive to Criticism - When someone challenges their principles or values, Advocates may react strongly. People with this personality type can become defensive in the face of criticism and conflict, particularly when it comes to issues that are near to their hearts.
			Reluctant to Open Up - Advocates value honesty, but they're also private. They may find it difficult to open up and be vulnerable about their struggles. This might also be because they think they need to solve their problems on their own or don't want to burden other people with their issues. When Advocates don't ask for help, they may inadvertently hold themselves back or create distance in their relationships.
			Perfectionistic - The Advocate personality type is all but defined by idealism. While this is a wonderful quality in many ways, an ideal situation is not always possible. Advocates might find it difficult to appreciate their jobs, living situations, or relationships if they're continually fixating on imperfections and wondering whether they should be looking for something better.
			Avoiding the Ordinary - Advocate personalities tend to be motivated by a sense of having a greater purpose in life. They might consider it tedious or unnecessary to break their big visions into small, manageable steps. But they may be setting themselves up for frustration if they don't turn their dreams into everyday routines and to-do lists. Without these specifics, their goals may never materialize.
			Prone to Burnout - Advocates' perfectionism and reserve may leave them with few options for letting off steam. People with this personality type can exhaust themselves if they don't find a way to balance their drive to help others with necessary self-care and rest.",
			"strength" => "Creative - Advocate personalities enjoy finding the perfect solution for the people they care about. To do this, they draw on their vivid imagination and their strong sense of compassion. This can make them excellent counselors and advisors.
			Insightful - Advocates typically strive to move past appearances and get to the heart of things. This can give them an almost uncanny ability to understand people's true motivations, feelings, and needs.
			Principled - People with the Advocate personality type tend to have deeply held beliefs, and their conviction often shines through when they speak or write about subjects that matter to them. Advocates can be compelling and inspiring communicators, with their idealism persuading even the hardest of skeptics.
			Passionate - Advocates can pursue their ideals with a single-mindedness that may catch others off guard. These personalities rarely settle for \"good enough,\" and their willingness to disrupt the status quo may not please everyone. That said, Advocates' passion for their chosen cause is a key aspect of their personality.
			Altruistic - Advocates generally aim to use their strengths for the greater good - they rarely enjoy succeeding at other people's expense. They tend to think about how their actions affect others, and their goal is to behave in a way that will help the people around them and make the world a better place.",
			"interpersonal_attributes" => "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores",
			"workplace_attributes" => "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores"
		],
		[
			"name" => "ENFJ",
			"breakdown" => "Extroverted Intuitive Feeling Judger",
			"definition" => "A Protagonist (ENFJ) is a person with the Extraverted, Intuitive, Feeling, and Judging personality traits. These warm, forthright types love helping others, and they tend to have strong ideas and values. They back their perspective with the creative energy to achieve their goals.

			Protagonists (ENFJs) feel called to serve a greater purpose in life. Thoughtful and idealistic, these personality types strive to have a positive impact on other people and the world around them. They rarely shy away from an opportunity to do the right thing, even when doing so is far from easy.",
			"weaknesses" => "Unrealistic - Many Protagonists put pressure on themselves to right every wrong that they encounter. But no matter how hard these personalities strive, it just isn't realistic for them to solve all of the world's problems. If they aren't careful, they can spread themselves too thin - and be left unable to help anyone.
			Overly Idealistic - Protagonists tend to have clear ideas about what's right and what's wrong. They often think that everyone shares these fundamental principles - or, at least, that everyone should share these principles. So it can come as a genuine shock to Protagonists when people violate their core values, such as truth or justice.
			Condescending - People with this personality type enjoy teaching others, particularly about the causes and beliefs that matter so much to them. But, at times, Protagonists' attempts to \"enlighten\" others may come across as patronizing - not the most effective strategy for persuading other people, unfortunately.
			Intense - When it comes to self-improvement, Protagonists are rarely short on energy or determination. But they may not recognize that not everyone shares these qualities. At times, Protagonists may push others to make changes that they aren't ready for - or simply aren't interested in making in the first place.
			Overly Empathetic - Compassion is among this personality type's greatest strengths. But Protagonists have a tendency to take on other people's problems as their own - a habit that can leave them emotionally and physically exhausted.",
			"strength" => "Receptive - Protagonists have strong opinions, but they're far from closed-minded. They recognize the importance of allowing others to express themselves fully. Even when Protagonists don't agree with someone, they recognize that person's right to voice their truth.
			Reliable - Few things bother Protagonists more than the prospect of letting down a person or cause that they believe in. People with this personality type can be counted on to see their promises and responsibilities through - even when it's difficult to do so.
			Passionate - Protagonists are far from being boring do-gooders. These types brim with interests, and they take great pleasure in pursuing their hobbies - whether that's hiking, cooking, dancing, growing houseplants, or something else entirely. As a result, they rarely find themselves at a loss for something interesting to do.
			Altruistic - These personalities are known for harboring a deep desire to be a force for positive change. Protagonists genuinely believe that if they bring people together, they can do a world of good.
			Charismatic - Determined and inspiring, Protagonists often find their way into leadership roles. Whether they're captain of their softball team or a leader on the world stage, they rarely lose sight of their main goal: to be of service to others.",
			"interpersonal_attributes" => "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores",
			"workplace_attributes" => "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores"
		],
		[
			"name" => "ISTJ",
			"breakdown" => "Introverted Sensing Thinking Judger",
			"definition" => "A Logistician (ISTJ) is someone with the Introverted, Observant, Thinking, and Judging personality traits. These people tend to be reserved yet willful, with a rational outlook on life. They compose their actions carefully and carry them out with methodical purpose.

			The Logistician personality type is thought to be the most abundant, making up around 13% of the population. Their defining characteristics of integrity, practical logic and tireless dedication to duty make Logisticians a vital core to many families, as well as organizations that uphold traditions, rules and standards, such as law offices, regulatory bodies and military. ",
			"weaknesses" => "Stubborn - The facts are the facts, and Logisticians tend to resist any new idea that isn't supported by them. This factual decision-making process also makes it difficult for people with the Logistician personality type to accept that they were wrong about something - but anyone can miss a detail, even them.
			Insensitive - While not intentionally harsh, Logisticians often hurt more sensitive types' feelings by the simple mantra that honesty is the best policy. Logistician personalities may take emotions into consideration, but really only so far as to determine the most effective way to say what needs to be said.
			Always by the Book - Logisticians believe that things work best with clearly defined rules, but this makes them reluctant to bend those rules or try new things, even when the downside is minimal. Truly unstructured environments leave Logisticians all but paralyzed.
			Judgmental - Opinions are opinions and facts are facts, and Logisticians are unlikely to respect people who disagree with those facts, or especially those who remain willfully ignorant of them.
			Often Unreasonably Blame Themselves - All this can combine to make Logisticians believe they are the only ones who can see projects through reliably. As they load themselves with extra work and responsibilities, turning away good intentions and helpful ideas, Logisticians sooner or later hit a tipping point where they simply can't deliver. ",
			"strength" => "Honest and Direct - Integrity is the heart of the Logistician personality type. Emotional manipulation, mind games and reassuring lies all run counter to Logisticians' preference for managing the reality of the situations they encounter with plain and simple honesty.
			Strong-willed and Dutiful - Logisticians embody that integrity in their actions too, working hard and staying focused on their goals. Patient and determined, people with the Logistician personality type meet their obligations, period.
			Very Responsible - Logisticians' word is a promise, and a promise means everything. Logisticians would rather run themselves into the ground with extra days and lost sleep than fail to deliver the results they said they would. Loyalty is a strong sentiment for Logistician personalities, and they fulfill their duties to the people and organizations they've committed themselves to.
			Calm and Practical - None of their promises would mean much if Logisticians lost their tempers and broke down at every sign of hardship - they keep their feet on the ground and make clear, rational decisions. Peoples' preferences are a factor to consider in this process, and Logisticians work to make the best use of individual qualities, but these decisions are made with effectiveness in mind more so than empathy. The same applies to criticisms, for others and themselves.
			Create and Enforce Order - The primary goal of any Logistician is to be effective in what they've chosen to do, and they believe that this is accomplished best when everyone involved knows exactly what is going on and why. Unclear guidelines and people who break established rules undermine this effort, and are rarely tolerated by Logisticians. Structure and rules foster dependability; chaos creates unforeseen setbacks and missed deadlines.
			Jacks-of-all-trades - Much like Analyst personality types, Logisticians are proud repositories of knowledge, though the emphasis is more on facts and statistics than concepts and underlying principles. This allows Logisticians to apply themselves to a variety of situations, picking up and applying new data and grasping the details of challenging situations as a matter of course.",
			"interpersonal_attributes" => "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores",
			"workplace_attributes" => "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores"
		],
		[
			"name" => "ESTJ",
			"breakdown" => "Extroverted Sensing Thinking Judger",
			"definition" => "An Executive (ESTJ) is someone with the Extraverted, Observant, Thinking, and Judging personality traits. They possess great fortitude, emphatically following their own sensible judgment. They often serve as a stabilizing force among others, able to offer solid direction amid adversity.

			Executives are representatives of tradition and order, utilizing their understanding of what is right, wrong and socially acceptable to bring families and communities together. Embracing the values of honesty, dedication and dignity, people with the Executive personality type are valued for their clear advice and guidance, and they happily lead the way on difficult paths. ",
			"weaknesses" => "Inflexible and Stubborn - The problem with being so fixated on what works is that Executives too often dismiss what might work better. Everything is opinion until proven, and Executive personalities are reluctant to trust an opinion long enough for it to have that chance.
			Uncomfortable with Unconventional Situations - Executives are strong adherents to tradition and when suddenly forced to try unvetted solutions, they become uncomfortable and stressed. New ideas suggest that their methods weren't good enough, and abandoning what has always worked before in favor of something that may yet fail risks their image of reliability.
			Judgmental - Executives have strong convictions about what is right, wrong, and socially acceptable. Executives' compulsion to create order often extends to all things and everyone, ignoring the possibility that there are two right ways to get things done. Executives do not hesitate to let these \"deviants\" know what they think, considering it their duty to set things right.
			Too Focused on Social Status - Executives take pride in the respect of their friends, colleagues and community and while difficult to admit, are very concerned with public opinion. Executives (especially Turbulent ones) can get so caught up in meeting others' expectations that they fail to address their own needs.
			Difficult to Relax - This need for respect fosters a need to maintain their dignity, which can make it difficult to cut loose and relax for risk of looking the fool, even in good fun.
			Difficulty Expressing Emotion - This is all evidence of Executives' greatest weakness: expressing emotions and feeling empathy. People with the Executive personality type get so caught up in the facts and most effective methods that they forget to think of what makes others happy, or of their sensitivity. ",
			"strength" => "Dedicated - Seeing things to completion borders on an ethical obligation for Executives. Tasks aren't simply abandoned because they've become difficult or boring - people with the Executive personality type take them up when they are the right thing to do, and they will be finished so long as they remain the right thing to do.
			Strong-willed - A strong will makes this dedication possible, and Executives don't give up their beliefs because of simple opposition. Executives defend their ideas and principles relentlessly, and must be proven clearly and conclusively wrong for their stance to budge.
			Direct and Honest - Executives trust facts far more than abstract ideas or opinions. Straightforward statements and information are king, and Executive personalities return the honesty (whether it's wanted or not).
			Loyal, Patient and Reliable - Executives work to exemplify truthfulness and reliability, considering stability and security very important. When Executives say they'll do something, they keep their word, making them very responsible members of their families, companies and communities.
			Enjoy Creating Order - Chaos makes things unpredictable, and unpredictable things can't be trusted when they are needed most - with this in mind, Executives strive to create order and security in their environments by establishing rules, structures and clear roles.
			Excellent Organizers - This commitment to truth and clear standards makes Executives capable and confident leaders. People with this personality type have no problem distributing tasks and responsibilities to others fairly and objectively, making them excellent administrators.",
			"interpersonal_attributes" => "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores",
			"workplace_attributes" => "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores"
		],
		[
			"name" => "ISFJ",
			"breakdown" => "Introverted Sensing Feeling Judger",
			"definition" => "A Defender (ISFJ) is someone with the Introverted, Observant, Feeling, and Judging personality traits. These people tend to be warm and unassuming in their own steady way. They're efficient and responsible, giving careful attention to practical details in their daily lives.

			The Defender personality type is quite unique, as many of their qualities defy the definition of their individual traits. Though sensitive, Defenders have excellent analytical abilities; though reserved, they have well-developed people skills and robust social relationships; and though they are generally a conservative type, Defenders are often receptive to change and new ideas. As with so many things, people with the Defender personality type are more than the sum of their parts, and it is the way they use these strengths that defines who they are.",
			"weaknesses" => "Humble and Shy - The meek shall inherit the earth, but it's a long road if they receive no recognition at all. This is possibly Defenders' biggest challenge, as they are so concerned with others' feelings that they refuse to make their thoughts known, or to take any duly earned credit for their contributions. Defenders' standards for themselves are also so high that, knowing they could have done some minor aspect of a task better, they often downplay their successes entirely.
			Take Things Too Personally - Defenders have trouble separating personal and impersonal situations - any situation is still an interaction between two people, after all - and any negativity from conflict or criticism can carry over from their professional to their personal lives, and back again.
			Repress Their Feelings - People with the Defender personality type are private and very sensitive, internalizing their feelings a great deal. Much in the way that Defenders protect others' feelings, they must protect their own, and this lack of healthy emotional expression can lead to a lot of stress and frustration.
			Overload Themselves - Their strong senses of duty and perfectionism combine with this aversion to emotional conflict to create a situation where it is far too easy for Defenders to overload themselves - or to be overloaded by others - as they struggle silently to meet everyone's expectations, especially their own.
			Reluctant to Change - These challenges can be particularly hard to address since Defender personalities value traditions and history highly in their decisions. A situation sometimes needs to reach a breaking point before Defenders are persuaded by circumstance, or the strong personality of a loved one, to alter course.
			Too Altruistic - This is all compounded and reinforced by Defenders' otherwise wonderful quality of altruism. Being such warm, good-natured people, Defenders are willing to let things slide, to believe that things will get better soon, to not burden others by accepting their offers of help, while their troubles mount unassisted.",
			"strength" => "Supportive - Defenders are the universal helpers, sharing their knowledge, experience, time and energy with anyone who needs it, and all the more so with friends and family. People with this personality type strive for win-win situations, choosing empathy over judgment whenever possible.
			Reliable and Patient - Rather than offering sporadic, excited rushes that leave things half finished, Defenders are meticulous and careful, taking a steady approach and bending with the needs of the situation just enough to accomplish their end goals. Defenders not only ensure that things are done to the highest standard, but often go well beyond what is required.
			Imaginative and Observant - Defenders are very imaginative, and use this quality as an accessory to empathy, observing others' emotional states and seeing things from their perspective. With their feet firmly planted on the ground, it is a very practical imagination, though they do find things quite fascinating and inspiring.
			Enthusiastic - When the goal is right, Defenders take all this support, reliability and imagination and apply it to something they believe will make a difference in people's lives - whether fighting poverty with a global initiative or simply making a customer's day.
			Loyal and Hard-Working - Given a little time, this enthusiasm grows into loyalty - Defender personalities often form an emotional attachment to the ideas and organizations they've dedicated themselves to. Anything short of meeting their obligations with good, hard work fails their own expectations.
			Good Practical Skills - The best part is, Defenders have the practical sense to actually do something with all this altruism. If mundane, routine tasks are what need to be done, Defenders can see the beauty and harmony that they create, because they know that it helps them to care for their friends, family, and anyone else who needs it.",
			"interpersonal_attributes" => "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores",
			"workplace_attributes" => "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores"
		],
		[
			"name" => "ESFJ",
			"breakdown" => "Extroverted Sensing Feeling Judger",
			"definition" => "A Consul (ESFJ) is a person with the Extraverted, Observant, Feeling, and Judging personality traits. They are attentive and people-focused, and they enjoy taking part in their social community. Their achievements are guided by decisive values, and they willingly offer guidance to others.

			People who share the Consul personality type are, for lack of a better word, popular - which makes sense, given that it is also a very common personality type, making up twelve percent of the population. In high school, Consuls are the cheerleaders and the quarterbacks, setting the tone, taking the spotlight and leading their teams forward to victory and fame. Later in life, Consuls continue to enjoy supporting their friends and loved ones, organizing social gatherings and doing their best to make sure everyone is happy.",
			"weaknesses" => "Worried about Their Social Status - These Strengths are related to a chief Weakness: Consuls' preoccupation with social status and influence, which affects many decisions they make, potentially limiting their creativity and open-mindedness.
			Inflexible - Consuls place a lot of importance on what is socially acceptable, and can be very cautious, even critical of anything unconventional or outside the mainstream. People with this personality type may also sometimes push their own beliefs too hard in an effort to establish them as mainstream.
			Reluctant to Innovate or Improvise - Just as they can be critical of others' \"unusual\" behavior, Consuls may also be unwilling to step out of their own comfort zones, usually for fear of being (or just appearing) different.
			Vulnerable to Criticism - It can be especially challenging to change these tendencies because Consuls are so conflict-averse. Consul personalities can become very defensive and hurt if someone, especially a person close to them, criticizes their habits, beliefs or traditions.
			Often Too Needy - Consuls need to hear and see a great deal of appreciation. If their efforts go unnoticed, people with the Consul personality type may start fishing for compliments, in an attempt to get reassurance of how much they are valued.
			Too Selfless - The other side of this is that Consuls sometimes try to establish their value with doting attention, something that can quickly overwhelm those who don't need it, making it ultimately unwelcome. Furthermore, Consuls often neglect their own needs in the process.",
			"strength" => "Strong Practical Skills - Consuls are excellent managers of day-to-day tasks and routine maintenance, enjoying making sure that those who are close to them are well cared for.
			Strong Sense of Duty - People with the Consul personality type have a strong sense of responsibility and strive to meet their obligations, though this may sometimes be more from a sense of social expectations than intrinsic drive.
			Very Loyal - Valuing stability and security very highly, Consuls are eager to preserve the status quo, which makes them extremely loyal and trustworthy partners and employees. Consuls are true pillars of any groups they belong to - whether it is their family or a community club, people with this personality type can always be relied upon.
			Sensitive and Warm - Helping to ensure that stability, Consul personalities seek harmony and care deeply about other people's feelings, being careful not to offend or hurt anybody. Consuls are strong team players, and win-win situations are the stuff smiles are made of.
			Good at Connecting with Others - These qualities come together to make Consuls social, comfortable and well-liked. Consul personalities have a strong need to \"belong\", and have no problem with small talk or following social cues in order to help them take an active role in their communities.",
			"interpersonal_attributes" => "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores",
			"workplace_attributes" => "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores"
		],
	],
	'indicators' => [
		[
			'name' => 'i',
			"description" => 'Often like working alone or in small groups, prefer a more deliberate pace, and like to focus at at task at a time',
		],
		[
			'name' => 'e',
			"description" => 'Extraverts are interested in engaging with their environment, and they feed off the responses of the people and events around them. ',
		],
		[
			'name' => 's',
			"description" => 'Tend to process things in a step-by-step linear sequence and observe and remember specific information',
		],
		[
			'name' => 't',
			"description" => 'Tend to make decisions using logical analysis, objectively weigh pros and cons, and value honesty, consistency, and fairness',
		],
		[
			'name' => 'f',
			"description" => 'Tend to be sensitive and cooperative, and decide based on their own personal values and will be affected by their actions.',
		],
		[
			'name' => 'j',
			"description" => 'Tend to be organized and prepared, like to make and stick to plans, and are comfortable following most rules.',
		],
		[
			'name' => 'n',
			"description" => 'Prefer to focus on posibilities and the big pictures, easily see patterns, value innovation, and seeks creative solutions to problems',
		],
		[
			'name' => 'p',
			"description" => 'Tend to make decisions using logical analysis, objectively weigh pros and cons, and value honesty, consistency, and fairness'
		],
	]
];
